name: modern_form_esys_flutter_share
description: A Flutter plugin for sharing images & text with other applications.
version: 1.0.0
repository: https://github.com/apps-auth/modern_form_esys_flutter_share
homepage: https://github.com/apps-auth/modern_form_esys_flutter_share

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.3

flutter:

  plugin:
    androidPackage: de.esys.esysfluttershare
    pluginClass: EsysFlutterSharePlugin